services:
  bot:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
    env_file:
      - .env
    networks:
      - db_network

  db:
    image: postgres
    env_file: .env
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network:
